### ISSUE TITLE
support for Xenial Ubuntu 16.04

### ISSUE THREAD

**Issue by lmorgen** [vikonava/rvm_passenger_nginx#1]
Currently the code raises an error, since it does not have a case for 16.04 in platform selection prior to fetching from the Phusion Passenger repo.

It's a trivial change to add the case.

**Comment by vikonava** [comment]
I agree on this, if you want you could include the lines and submit a Pull Request for this or I will fix it in the next weeks

**Comment by lmorgen** [comment]
Great. I've submitted a simple pull request.

**Comment by vikonava** [comment]
Pull request has been merged: https://github.com/vikonava/rvm_passenger_nginx/pull/2

Thanks
